"""Add proactive memory models

Revision ID: 02e961b9997d
Revises: 371092c79315
Create Date: 2025-08-16 15:16:05.095650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e961b9997d'
down_revision: Union[str, Sequence[str], None] = '371092c79315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('twitter_handle', sa.String(), nullable=True),
    sa.Column('slack_handle', sa.String(), nullable=True),
    sa.Column('linkedin_profile', sa.String(), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_user_fullname', 'contacts', ['user_id', 'first_name', 'last_name'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('task', 'meeting', 'deadline', 'follow_up', 'promise', 'reminder', name='commitmenttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', 'cancelled', name='commitmentstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('committed_by', sa.UUID(), nullable=False),
    sa.Column('committed_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_thread_id', sa.UUID(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['committed_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['committed_to'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commitment_contact', 'commitments', ['committed_to'], unique=False)
    op.create_index('ix_commitment_due_date', 'commitments', ['due_date'], unique=False)
    op.create_index('ix_commitment_user_status', 'commitments', ['committed_by', 'status'], unique=False)
    op.create_table('contact_dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_interaction', sa.DateTime(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_threads', sa.Integer(), nullable=True),
    sa.Column('relationship_strength', sa.Float(), nullable=True),
    sa.Column('communication_style', sa.String(length=100), nullable=True),
    sa.Column('interaction_frequency', sa.String(length=50), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('common_entities', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('personality_insights', sa.Text(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_index('ix_contact_dossier_updated', 'contact_dossiers', ['last_updated'], unique=False)
    op.create_index('ix_contact_dossier_user', 'contact_dossiers', ['user_id'], unique=False)
    op.create_table('contact_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_thread_id', sa.UUID(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('extracted_topics', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_reference_filename', 'file_references', ['filename'], unique=False)
    op.create_index('ix_file_reference_shared_at', 'file_references', ['shared_at'], unique=False)
    op.create_index('ix_file_reference_user', 'file_references', ['shared_by'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('follow_up', 'deadline_reminder', 'reconnection', 'file_reference', 'relationship_insight', 'commitment_check', name='nudgetype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='nudgepriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_commitment_id', sa.UUID(), nullable=True),
    sa.Column('related_file_id', sa.UUID(), nullable=True),
    sa.Column('related_thread_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('is_acted_upon', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['related_commitment_id'], ['commitments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_file_id'], ['file_references.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nudge_priority_scheduled', 'nudges', ['priority', 'scheduled_for'], unique=False)
    op.create_index('ix_nudge_type_user', 'nudges', ['type', 'user_id'], unique=False)
    op.create_index('ix_nudge_user_delivered', 'nudges', ['user_id', 'is_delivered'], unique=False)
    op.drop_constraint('summaries_scope_id_fkey', 'summaries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('summaries_scope_id_fkey', 'summaries', 'threads', ['scope_id'], ['id'])
    op.drop_index('ix_nudge_user_delivered', table_name='nudges')
    op.drop_index('ix_nudge_type_user', table_name='nudges')
    op.drop_index('ix_nudge_priority_scheduled', table_name='nudges')
    op.drop_table('nudges')
    op.drop_index('ix_file_reference_user', table_name='file_references')
    op.drop_index('ix_file_reference_shared_at', table_name='file_references')
    op.drop_index('ix_file_reference_filename', table_name='file_references')
    op.drop_table('file_references')
    op.drop_table('contact_memory')
    op.drop_index('ix_contact_dossier_user', table_name='contact_dossiers')
    op.drop_index('ix_contact_dossier_updated', table_name='contact_dossiers')
    op.drop_table('contact_dossiers')
    op.drop_index('ix_commitment_user_status', table_name='commitments')
    op.drop_index('ix_commitment_due_date', table_name='commitments')
    op.drop_index('ix_commitment_contact', table_name='commitments')
    op.drop_table('commitments')
    op.drop_index('ix_contact_user_fullname', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('users')
    # ### end Alembic commands ###
