"""Add multi-tenant architecture with tenant isolation

Revision ID: 286e0aff414f
Revises: 550d022883b1
Create Date: 2025-08-17 12:00:02.181590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286e0aff414f'
down_revision: Union[str, Sequence[str], None] = '550d022883b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_messages_platform_timestamp', table_name='messages')
    op.drop_index('ix_messages_sender_timestamp', table_name='messages')
    op.drop_index('ix_messages_thread_timestamp', table_name='messages')
    op.drop_constraint('uq_platform_message', 'messages', type_='unique')
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_messages_tenant_platform_timestamp', 'messages', ['tenant_id', 'platform', 'timestamp'], unique=False)
    op.create_index('ix_messages_tenant_sender_timestamp', 'messages', ['tenant_id', 'sender_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_tenant_thread_timestamp', 'messages', ['tenant_id', 'thread_id', 'timestamp'], unique=False)
    op.create_unique_constraint('uq_tenant_platform_message', 'messages', ['tenant_id', 'platform', 'platform_message_id'])
    op.add_column('participants', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_participants_display_name', table_name='participants')
    op.drop_index('ix_participants_email', table_name='participants')
    op.drop_index('ix_participants_platform', table_name='participants')
    op.drop_constraint('uq_platform_participant', 'participants', type_='unique')
    op.create_index('ix_participants_tenant_display_name', 'participants', ['tenant_id', 'display_name'], unique=False)
    op.create_index('ix_participants_tenant_email', 'participants', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_participants_tenant_id', 'participants', ['tenant_id'], unique=False)
    op.create_index('ix_participants_tenant_platform', 'participants', ['tenant_id', 'platform'], unique=False)
    op.create_unique_constraint('uq_tenant_platform_participant', 'participants', ['tenant_id', 'platform', 'platform_user_id'])
    op.add_column('threads', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_threads_last_message', table_name='threads')
    op.drop_index('ix_threads_platform', table_name='threads')
    op.drop_constraint('uq_platform_thread', 'threads', type_='unique')
    op.create_index(op.f('ix_threads_tenant_id'), 'threads', ['tenant_id'], unique=False)
    op.create_index('ix_threads_tenant_last_message', 'threads', ['tenant_id', 'last_message_at'], unique=False)
    op.create_index('ix_threads_tenant_platform', 'threads', ['tenant_id', 'platform'], unique=False)
    op.create_unique_constraint('uq_tenant_platform_thread', 'threads', ['tenant_id', 'platform', 'platform_thread_id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('user_metadata', sa.JSON(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_system_admin', 'users', ['is_system_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_system_admin', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'user_metadata')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'is_system_admin')
    op.drop_column('users', 'is_active')
    op.drop_constraint('uq_tenant_platform_thread', 'threads', type_='unique')
    op.drop_index('ix_threads_tenant_platform', table_name='threads')
    op.drop_index('ix_threads_tenant_last_message', table_name='threads')
    op.drop_index(op.f('ix_threads_tenant_id'), table_name='threads')
    op.create_unique_constraint('uq_platform_thread', 'threads', ['platform', 'platform_thread_id'])
    op.create_index('ix_threads_platform', 'threads', ['platform'], unique=False)
    op.create_index('ix_threads_last_message', 'threads', ['last_message_at'], unique=False)
    op.drop_column('threads', 'tenant_id')
    op.drop_constraint('uq_tenant_platform_participant', 'participants', type_='unique')
    op.drop_index('ix_participants_tenant_platform', table_name='participants')
    op.drop_index('ix_participants_tenant_id', table_name='participants')
    op.drop_index('ix_participants_tenant_email', table_name='participants')
    op.drop_index('ix_participants_tenant_display_name', table_name='participants')
    op.create_unique_constraint('uq_platform_participant', 'participants', ['platform', 'platform_user_id'])
    op.create_index('ix_participants_platform', 'participants', ['platform'], unique=False)
    op.create_index('ix_participants_email', 'participants', ['email'], unique=False)
    op.create_index('ix_participants_display_name', 'participants', ['display_name'], unique=False)
    op.drop_column('participants', 'tenant_id')
    op.drop_constraint('uq_tenant_platform_message', 'messages', type_='unique')
    op.drop_index('ix_messages_tenant_thread_timestamp', table_name='messages')
    op.drop_index('ix_messages_tenant_sender_timestamp', table_name='messages')
    op.drop_index('ix_messages_tenant_platform_timestamp', table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.create_unique_constraint('uq_platform_message', 'messages', ['platform', 'platform_message_id'])
    op.create_index('ix_messages_thread_timestamp', 'messages', ['thread_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_sender_timestamp', 'messages', ['sender_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_platform_timestamp', 'messages', ['platform', 'timestamp'], unique=False)
    op.drop_column('messages', 'tenant_id')
    # ### end Alembic commands ###
