"""add_audit_log_table_v2

Revision ID: bb04e9c4a9aa
Revises: 796f64ab150e
Create Date: 2025-08-16 22:49:30.027743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb04e9c4a9aa'
down_revision: Union[str, Sequence[str], None] = '796f64ab150e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('event_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('event_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('action', sa.String(length=100), nullable=False),
                    sa.Column('user_id', sa.String(length=255), nullable=True),
                    sa.Column('resource_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('resource_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('severity', sa.String(
                        length=20), nullable=False),
                    sa.Column('timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('details', sa.JSON(), nullable=True),
                    sa.Column('ip_address', sa.String(
                        length=45), nullable=True),
                    sa.Column('user_agent', sa.Text(), nullable=True),
                    sa.Column('session_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('success', sa.Boolean(), nullable=False),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.Column('integrity_hash', sa.String(
                        length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_audit_logs_action'),
                    'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'),
                    'audit_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_event_type'),
                    'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'),
                    'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'),
                    'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'),
                    'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'),
                    'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'),
                    'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'),
                    'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
