"""
Summary Model

Represents AI-generated summaries of threads and conversations.
"""

from sqlalchemy import Column, String, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from db.base import Base


class Summary(Base):
    """
    Summary model for AI-generated summaries.
    
    Stores summaries generated by AI for threads, conversations,
    or groups of messages.
    
    Attributes:
        thread_id: Foreign key to Thread (nullable for other summary types)
        summary_type: Type of summary (brief, detailed, insight, etc.)
        content: The summary text
        summary_metadata: Additional summary information
        thread: Related thread (if applicable)
    """
    
    __tablename__ = "summaries"
    
    # Foreign key to thread (nullable for non-thread summaries)
    thread_id = Column(
        UUID(as_uuid=True),
        ForeignKey("threads.id", ondelete="CASCADE"),
        nullable=True,
        index=True
    )
    
    # Summary type
    summary_type = Column(String(50), nullable=False, index=True)
    
    # Summary content
    content = Column(Text, nullable=False)
    
    # Additional metadata
    # Structure: {
    #   "model": "ollama/llama3.2:3b",
    #   "tokens_used": 150,
    #   "generation_time": 2.5,
    #   "message_count": 10,
    #   "date_range": {"start": "...", "end": "..."},
    #   "key_topics": [...],
    #   "sentiment": "positive|neutral|negative",
    #   ...
    # }
    summary_metadata = Column(JSONB, nullable=True)
    
    # Relationships
    thread = relationship("Thread")
    
    def __repr__(self) -> str:
        return f"<Summary(id={self.id}, type={self.summary_type})>"
