appservice:
  address: http://localhost:29319
  as_token: test_token_123
  bot:
    avatar: mxc://maunium.net/JxjlbZUlCPULEeHZSwleUXQv
    displayname: Instagram Bridge Bot
    username: instagrambot
  database:
    type: sqlite3
    uri: ./test_bridges/instagram/meta.db
  hostname: 0.0.0.0
  hs_token: test_token_123
  id: instagram
  port: 29319
bridge:
  displayname_template: '{displayname} (Instagram)'
  permissions:
    '*': relay
    '@testuser:example.com': admin
    matrix.example.com: user
  personal_filtering_spaces: false
  portal_message_buffer: 128
  sync_direct_chat_list: false
  username_template: instagram_{userid}
homeserver:
  address: https://matrix.example.com
  domain: matrix.example.com
logging:
  formatters:
    colored:
      (): mautrix.util.ColorFormatter
      format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
    normal:
      format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: colored
    file:
      backupCount: 10
      class: logging.handlers.RotatingFileHandler
      filename: ./logs/instagram.log
      formatter: normal
      maxBytes: 10485760
  loggers:
    mau:
      level: DEBUG
  root:
    handlers:
    - file
    - console
    level: DEBUG
  version: 1
meta:
  mode: instagram
