"""Initial schema with all models

Revision ID: cd551087417f
Revises:
Create Date: 2025-11-11 08:09:27.522247

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd551087417f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("emails", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("phones", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "platform_identities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "contact_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_canonical_name"), "contacts", ["canonical_name"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_created_at"), "contacts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "participants",
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "participant_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_user_id", name="uq_platform_user"),
    )
    op.create_index(
        op.f("ix_participants_contact_id"), "participants", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_participants_created_at"), "participants", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_participants_email"), "participants", ["email"], unique=False
    )
    op.create_index(op.f("ix_participants_id"), "participants", ["id"], unique=False)
    op.create_index(
        op.f("ix_participants_phone"), "participants", ["phone"], unique=False
    )
    op.create_index(
        op.f("ix_participants_platform"), "participants", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_participants_platform_user_id"),
        "participants",
        ["platform_user_id"],
        unique=False,
    )
    op.create_table(
        "platform_connections",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "GMAIL",
                "SLACK",
                "DISCORD",
                "WHATSAPP",
                "TWITTER",
                "TELEGRAM",
                name="platform_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "credentials", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "EXPIRED",
                "FAILED",
                "REVOKED",
                name="connection_status",
            ),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column(
            "platform_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_connections_created_at"),
        "platform_connections",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_connections_id"), "platform_connections", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_connections_platform"),
        "platform_connections",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_connections_status"),
        "platform_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_connections_user_id"),
        "platform_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "threads",
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_thread_id", sa.String(length=255), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("participant_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("first_message_at", sa.DateTime(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "platform_thread_id", name="uq_platform_thread"
        ),
    )
    op.create_index(
        op.f("ix_threads_contact_id"), "threads", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_threads_created_at"), "threads", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_threads_first_message_at"),
        "threads",
        ["first_message_at"],
        unique=False,
    )
    op.create_index(op.f("ix_threads_id"), "threads", ["id"], unique=False)
    op.create_index(
        op.f("ix_threads_last_message_at"), "threads", ["last_message_at"], unique=False
    )
    op.create_index(op.f("ix_threads_platform"), "threads", ["platform"], unique=False)
    op.create_index(
        op.f("ix_threads_platform_thread_id"),
        "threads",
        ["platform_thread_id"],
        unique=False,
    )
    op.create_table(
        "collection_jobs",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum("HISTORICAL", "REALTIME", "INCREMENTAL", name="job_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["platform_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_jobs_connection_id"),
        "collection_jobs",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_jobs_created_at"),
        "collection_jobs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_jobs_id"), "collection_jobs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_jobs_job_type"),
        "collection_jobs",
        ["job_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_jobs_status"), "collection_jobs", ["status"], unique=False
    )
    op.create_table(
        "raw_messages",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_message_id", sa.String(length=255), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["platform_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "platform_message_id",
            name="uq_connection_platform_message",
        ),
    )
    op.create_index(
        op.f("ix_raw_messages_connection_id"),
        "raw_messages",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_messages_created_at"), "raw_messages", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_raw_messages_id"), "raw_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_raw_messages_platform"), "raw_messages", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_raw_messages_platform_message_id"),
        "raw_messages",
        ["platform_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_messages_processed"), "raw_messages", ["processed"], unique=False
    )
    op.create_table(
        "summaries",
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("summary_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "summary_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summaries_created_at"), "summaries", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_summaries_id"), "summaries", ["id"], unique=False)
    op.create_index(
        op.f("ix_summaries_summary_type"), "summaries", ["summary_type"], unique=False
    )
    op.create_index(
        op.f("ix_summaries_thread_id"), "summaries", ["thread_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("raw_message_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_message_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("cleaned_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["platform_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"], ["raw_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["participants.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "platform_message_id",
            name="uq_connection_normalized_message",
        ),
    )
    op.create_index(
        op.f("ix_messages_connection_id"), "messages", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_platform"), "messages", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_messages_platform_message_id"),
        "messages",
        ["platform_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_raw_message_id"), "messages", ["raw_message_id"], unique=True
    )
    op.create_index(
        op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_timestamp"), "messages", ["timestamp"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("platform_url", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachments_created_at"), "attachments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.create_index(
        op.f("ix_attachments_message_id"), "attachments", ["message_id"], unique=False
    )
    op.create_table(
        "embeddings",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("vector", postgresql.ARRAY(sa.Float()), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embeddings_created_at"), "embeddings", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_embeddings_id"), "embeddings", ["id"], unique=False)
    op.create_index(
        op.f("ix_embeddings_message_id"), "embeddings", ["message_id"], unique=True
    )
    op.create_table(
        "entities",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_text", sa.String(length=500), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "entity_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entities_created_at"), "entities", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_entities_entity_text"), "entities", ["entity_text"], unique=False
    )
    op.create_index(
        op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_entities_id"), "entities", ["id"], unique=False)
    op.create_index(
        op.f("ix_entities_message_id"), "entities", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entities_message_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_text"), table_name="entities")
    op.drop_index(op.f("ix_entities_created_at"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_embeddings_message_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_created_at"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_attachments_message_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_created_at"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_messages_timestamp"), table_name="messages")
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_raw_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_platform_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_platform"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_connection_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_summaries_thread_id"), table_name="summaries")
    op.drop_index(op.f("ix_summaries_summary_type"), table_name="summaries")
    op.drop_index(op.f("ix_summaries_id"), table_name="summaries")
    op.drop_index(op.f("ix_summaries_created_at"), table_name="summaries")
    op.drop_table("summaries")
    op.drop_index(op.f("ix_raw_messages_processed"), table_name="raw_messages")
    op.drop_index(
        op.f("ix_raw_messages_platform_message_id"), table_name="raw_messages"
    )
    op.drop_index(op.f("ix_raw_messages_platform"), table_name="raw_messages")
    op.drop_index(op.f("ix_raw_messages_id"), table_name="raw_messages")
    op.drop_index(op.f("ix_raw_messages_created_at"), table_name="raw_messages")
    op.drop_index(op.f("ix_raw_messages_connection_id"), table_name="raw_messages")
    op.drop_table("raw_messages")
    op.drop_index(op.f("ix_collection_jobs_status"), table_name="collection_jobs")
    op.drop_index(op.f("ix_collection_jobs_job_type"), table_name="collection_jobs")
    op.drop_index(op.f("ix_collection_jobs_id"), table_name="collection_jobs")
    op.drop_index(op.f("ix_collection_jobs_created_at"), table_name="collection_jobs")
    op.drop_index(
        op.f("ix_collection_jobs_connection_id"), table_name="collection_jobs"
    )
    op.drop_table("collection_jobs")
    op.drop_index(op.f("ix_threads_platform_thread_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_platform"), table_name="threads")
    op.drop_index(op.f("ix_threads_last_message_at"), table_name="threads")
    op.drop_index(op.f("ix_threads_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_first_message_at"), table_name="threads")
    op.drop_index(op.f("ix_threads_created_at"), table_name="threads")
    op.drop_index(op.f("ix_threads_contact_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(
        op.f("ix_platform_connections_user_id"), table_name="platform_connections"
    )
    op.drop_index(
        op.f("ix_platform_connections_status"), table_name="platform_connections"
    )
    op.drop_index(
        op.f("ix_platform_connections_platform"), table_name="platform_connections"
    )
    op.drop_index(op.f("ix_platform_connections_id"), table_name="platform_connections")
    op.drop_index(
        op.f("ix_platform_connections_created_at"), table_name="platform_connections"
    )
    op.drop_table("platform_connections")
    op.drop_index(op.f("ix_participants_platform_user_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_platform"), table_name="participants")
    op.drop_index(op.f("ix_participants_phone"), table_name="participants")
    op.drop_index(op.f("ix_participants_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_email"), table_name="participants")
    op.drop_index(op.f("ix_participants_created_at"), table_name="participants")
    op.drop_index(op.f("ix_participants_contact_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_created_at"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_canonical_name"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
