"""add_linkedin_and_message_count_to_contacts

Revision ID: 045e54df57ce
Revises: f7dd59589c03
Create Date: 2025-12-23 15:19:05.408556

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "045e54df57ce"
down_revision: Union[str, None] = "f7dd59589c03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("linkedin_url", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("linkedin_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("company", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("job_title", sa.String(length=255), nullable=True)
    )
    # Add message_count with server_default to handle existing rows
    op.add_column(
        "contacts",
        sa.Column("message_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("contacts", "user_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_contacts_company"), "contacts", ["company"], unique=False)
    op.create_index(
        op.f("ix_contacts_linkedin_id"), "contacts", ["linkedin_id"], unique=True
    )
    op.create_index(
        op.f("ix_contacts_linkedin_url"), "contacts", ["linkedin_url"], unique=True
    )
    op.create_index(
        op.f("ix_contacts_message_count"), "contacts", ["message_count"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_message_count"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_linkedin_url"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_linkedin_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company"), table_name="contacts")
    op.alter_column("contacts", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("contacts", "message_count")
    op.drop_column("contacts", "job_title")
    op.drop_column("contacts", "company")
    op.drop_column("contacts", "linkedin_id")
    op.drop_column("contacts", "linkedin_url")
    # ### end Alembic commands ###
