/**
 * Nudge Notification Center (Section 4.11.7)
 * 
 * Displays proactive nudges generated by MESH's memory agent.
 * Includes commitment reminders, follow-up suggestions, and reconnection prompts.
 */

import React, { useState } from 'react';
import {
    StyleSheet,
    View,
    Text,
    ScrollView,
    TouchableOpacity,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../../src/theme';
import { Card } from '../../components/Card/Card';
import { DUMMY_NUDGES } from '../../src/data/dummyData';

type NudgeType = 'commitment_reminder' | 'follow_up' | 'reconnection';
type NudgePriority = 'high' | 'medium' | 'low';

const TYPE_CONFIG: Record<NudgeType, { icon: string; color: string; label: string }> = {
    commitment_reminder: { icon: 'calendar', color: '#F59E0B', label: 'Commitment' },
    follow_up: { icon: 'chatbubble-ellipses', color: '#3B82F6', label: 'Follow-up' },
    reconnection: { icon: 'people', color: '#8B5CF6', label: 'Reconnection' },
};

const PRIORITY_CONFIG: Record<NudgePriority, { borderColor: string; bgColor: string }> = {
    high: { borderColor: '#F59E0B', bgColor: '#FFFBEB' },
    medium: { borderColor: '#3B82F6', bgColor: '#EFF6FF' },
    low: { borderColor: '#9CA3AF', bgColor: theme.colors.background },
};

export default function NudgesScreen() {
    const insets = useSafeAreaInsets();
    const [dismissedNudges, setDismissedNudges] = useState<string[]>([]);

    const activeNudges = DUMMY_NUDGES.filter(n => !dismissedNudges.includes(n.id));
    const pastNudges = dismissedNudges.length;

    const handleDismiss = (nudgeId: string) => {
        setDismissedNudges(prev => [...prev, nudgeId]);
    };

    const handleAction = (nudgeId: string, action: string) => {
        console.log('Action:', action, 'for nudge:', nudgeId);
        // In real app, this would trigger the appropriate action
        if (action === 'dismiss' || action === 'complete') {
            handleDismiss(nudgeId);
        }
    };

    const formatCreatedTime = (timestamp: string) => {
        const date = new Date(timestamp);
        const now = new Date();
        const diffHours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
        const diffDays = Math.floor(diffHours / 24);

        if (diffHours < 1) return 'Just now';
        if (diffHours < 24) return `${diffHours}h ago`;
        if (diffDays === 1) return 'Yesterday';
        return `${diffDays} days ago`;
    };

    return (
        <View style={styles.container}>
            {/* Header Summary */}
            <View style={styles.header}>
                <View style={styles.headerContent}>
                    <View style={styles.headerIcon}>
                        <Ionicons name="notifications" size={28} color={theme.colors.primary} />
                    </View>
                    <View>
                        <Text style={styles.headerTitle}>Proactive Nudges</Text>
                        <Text style={styles.headerSubtitle}>
                            {activeNudges.length} active • {pastNudges} dismissed this week
                        </Text>
                    </View>
                </View>
            </View>

            <ScrollView style={styles.listContainer} showsVerticalScrollIndicator={false}>
                {/* Active Nudges Section */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Requiring Attention</Text>

                    {activeNudges.length === 0 ? (
                        <View style={styles.emptyState}>
                            <Ionicons name="checkmark-circle-outline" size={48} color={theme.colors.success} />
                            <Text style={styles.emptyTitle}>All Caught Up!</Text>
                            <Text style={styles.emptySubtitle}>No pending nudges at the moment</Text>
                        </View>
                    ) : (
                        activeNudges.map((nudge) => {
                            const typeConfig = TYPE_CONFIG[nudge.type];
                            const priorityConfig = PRIORITY_CONFIG[nudge.priority];

                            return (
                                <Card
                                    key={nudge.id}
                                    style={[
                                        styles.nudgeCard,
                                        {
                                            borderLeftWidth: 4,
                                            borderLeftColor: priorityConfig.borderColor,
                                            backgroundColor: priorityConfig.bgColor,
                                        }
                                    ]}
                                >
                                    {/* Nudge Header */}
                                    <View style={styles.nudgeHeader}>
                                        <View style={[styles.typeIcon, { backgroundColor: typeConfig.color + '20' }]}>
                                            <Ionicons name={typeConfig.icon as any} size={18} color={typeConfig.color} />
                                        </View>
                                        <View style={styles.nudgeHeaderText}>
                                            <Text style={styles.nudgeType}>{typeConfig.label}</Text>
                                            <Text style={styles.nudgeTime}>{formatCreatedTime(nudge.createdAt)}</Text>
                                        </View>
                                        <TouchableOpacity
                                            style={styles.dismissButton}
                                            onPress={() => handleDismiss(nudge.id)}
                                        >
                                            <Ionicons name="close" size={18} color={theme.colors.textTertiary} />
                                        </TouchableOpacity>
                                    </View>

                                    {/* Nudge Content */}
                                    <Text style={styles.nudgeTitle}>{nudge.title}</Text>
                                    <Text style={styles.nudgeMessage}>{nudge.message}</Text>

                                    {/* Suggested Actions */}
                                    <View style={styles.actionsContainer}>
                                        {nudge.suggestedActions.map((action, idx) => (
                                            <TouchableOpacity
                                                key={idx}
                                                style={[
                                                    styles.actionButton,
                                                    idx === 0 && styles.primaryAction,
                                                ]}
                                                onPress={() => handleAction(nudge.id, action.action)}
                                            >
                                                <Text style={[
                                                    styles.actionText,
                                                    idx === 0 && styles.primaryActionText,
                                                ]}>
                                                    {action.label}
                                                </Text>
                                            </TouchableOpacity>
                                        ))}
                                    </View>
                                </Card>
                            );
                        })
                    )}
                </View>

                {/* Past Nudges Section (Collapsed) */}
                {pastNudges > 0 && (
                    <View style={styles.section}>
                        <TouchableOpacity style={styles.pastNudgesHeader}>
                            <View style={styles.pastNudgesLeft}>
                                <Ionicons name="archive-outline" size={20} color={theme.colors.textSecondary} />
                                <Text style={styles.pastNudgesText}>
                                    {pastNudges} Past Nudges
                                </Text>
                            </View>
                            <Ionicons name="chevron-forward" size={20} color={theme.colors.textTertiary} />
                        </TouchableOpacity>
                    </View>
                )}

                {/* Info Card */}
                <View style={styles.section}>
                    <Card style={styles.infoCard}>
                        <Ionicons name="bulb-outline" size={24} color={theme.colors.primary} />
                        <View style={styles.infoContent}>
                            <Text style={styles.infoTitle}>How Nudges Work</Text>
                            <Text style={styles.infoText}>
                                MESH automatically detects commitments, unanswered messages, and contacts you haven't spoken to in a while, then gently reminds you at the right time.
                            </Text>
                        </View>
                    </Card>
                </View>

                <View style={{ height: insets.bottom + 40 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.backgroundSecondary,
    },
    header: {
        backgroundColor: theme.colors.background,
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    headerIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: theme.colors.primaryLighter,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    headerSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    listContainer: {
        flex: 1,
    },
    section: {
        padding: 16,
    },
    sectionTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        marginBottom: 12,
    },
    nudgeCard: {
        marginBottom: 12,
        padding: 16,
    },
    nudgeHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    typeIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    nudgeHeaderText: {
        flex: 1,
        marginLeft: 12,
    },
    nudgeType: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
    },
    nudgeTime: {
        fontSize: 11,
        color: theme.colors.textTertiary,
        marginTop: 1,
    },
    dismissButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: theme.colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    nudgeTitle: {
        fontSize: 17,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 6,
    },
    nudgeMessage: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
        marginBottom: 16,
    },
    actionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    actionButton: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: theme.colors.surface,
    },
    primaryAction: {
        backgroundColor: theme.colors.primary,
    },
    actionText: {
        fontSize: 13,
        fontWeight: '500',
        color: theme.colors.text,
    },
    primaryActionText: {
        color: 'white',
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
        backgroundColor: theme.colors.background,
        borderRadius: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        marginTop: 12,
    },
    emptySubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    pastNudgesHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: theme.colors.background,
        borderRadius: 12,
    },
    pastNudgesLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    pastNudgesText: {
        fontSize: 15,
        color: theme.colors.textSecondary,
    },
    infoCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 16,
        padding: 16,
        backgroundColor: theme.colors.primaryLighter,
    },
    infoContent: {
        flex: 1,
    },
    infoTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 4,
    },
    infoText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 19,
    },
});
